#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-bot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Google_Vertex (LLM)
- Deepgram (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.evals.transport import EvalTransportParams
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.deepgram.tts import DeepgramTTSService
from pipecat.services.google.vertex.llm import GoogleVertexLLMService
from pipecat.services.llm_service import FunctionCallParams
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.workers.runner import WorkerRunner

from library import LibraryCatalog

load_dotenv(override=True)


LIBRARIAN_INSTRUCTION = """You are the Aryan Retail librarian in a voice conversation.
You help people find books, rent available books, receive returned books, and list a
member's current loans. Use the catalog tools for every availability, rental, return,
or loan-status claim. Do not claim a rental or return succeeded until its tool reports
success. To rent a book, obtain both its title and the member's name. Keep responses
short, natural, and easy to speak: no markdown, emojis, or bullet points."""


def required_env(name: str) -> str:
    """Return a required configuration value with an actionable startup error."""
    value = os.getenv(name)
    if not value:
        raise ValueError(f"Missing required environment variable: {name}")
    return value


async def search_books(params: FunctionCallParams, query: str) -> None:
    """Search the library catalog by book title or author.

    Args:
        query: The title, author, or partial title the member is looking for.
    """
    catalog: LibraryCatalog = params.app_resources
    await params.result_callback({"books": catalog.search(query)})


async def rent_book(params: FunctionCallParams, title: str, member_name: str) -> None:
    """Rent one available book to a library member.

    Args:
        title: The exact title the member wants to rent.
        member_name: The member's name for the rental record.
    """
    catalog: LibraryCatalog = params.app_resources
    await params.result_callback(catalog.rent(title, member_name))


async def receive_book(params: FunctionCallParams, title: str) -> None:
    """Receive a rented book that a member is returning.

    Args:
        title: The exact title being returned to the library.
    """
    catalog: LibraryCatalog = params.app_resources
    await params.result_callback(catalog.receive(title))


async def list_member_loans(params: FunctionCallParams, member_name: str) -> None:
    """List all books that are currently rented by a member.

    Args:
        member_name: The member whose current rentals should be listed.
    """
    catalog: LibraryCatalog = params.app_resources
    await params.result_callback({"books": catalog.loans_for(member_name)})


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=required_env("DEEPGRAM_API_KEY"))

    # Text-to-Speech service
    tts = DeepgramTTSService(
        api_key=required_env("DEEPGRAM_API_KEY"),
        settings=DeepgramTTSService.Settings(
            voice=required_env("DEEPGRAM_VOICE_ID"),
        ),
    )

    # LLM service
    llm = GoogleVertexLLMService(
        project_id=required_env("VERTEX_PROJECT_ID"),
        credentials_path=required_env("VERTEX_CREDENTIALS_PATH"),
        location=os.getenv("VERTEX_LOCATION", "asia-south1"),
        settings=GoogleVertexLLMService.Settings(
            model=os.getenv("VERTEX_MODEL", "gemini-2.5-flash"),
            system_instruction=LIBRARIAN_INSTRUCTION,
            temperature=0.0,
        ),
    )

    context = LLMContext(
        tools=[search_books, rent_book, receive_book, list_member_loans],
    )
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=SileroVADAnalyzer()),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
        app_resources=LibraryCatalog(),
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message(
            {
                "role": "developer",
                "content": (
                    "Say exactly: Welcome to Aryan Retail Library. I can help you "
                    "find, rent, or return a book."
                ),
            }
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Behavioral evals: run with `-t eval` to drive this bot via `pipecat eval`.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
